#find

	if app.ENABLE_MAGIC_REDUCTION_SYSTEM:
		AFFECT_DICT.update({
			item.APPLY_RESIST_MAGIC_REDUCTION : localeInfo.TOOLTIP_RESIST_MAGIC_REDUCTION,
		})


#add after


	if app.ENABLE_S_B_SYSTEM:
		AFFECT_DICT[item.APPLY_ATTBONUS_STONE]	= localeInfo.TOOLTIP_APPLY_ATTBONUS_STONE
		AFFECT_DICT[item.APPLY_ATTBONUS_BOSS]	= localeInfo.TOOLTIP_APPLY_ATTBONUS_BOSS